/*
 *  Autogenerated with cproto on:  Thu May 8 12:58:52 BST 2008
 */

struct vmfs_request;
struct sock;
struct statfs;

/* proc.c */
extern int vmfs_errno(int error);
extern int vmfs_open(struct dentry *dentry, int flags, int wish);
extern int vmfs_close(struct inode *ino);
extern int vmfs_close_fileid(struct dentry *dentry, int32_t fileid);
extern int vmfs_proc_create(struct dentry *dentry, uint32_t mode, int32_t *fileid);
extern int vmfs_proc_mv(struct dentry *old_dentry, struct dentry *new_dentry);
extern int vmfs_proc_mkdir(struct dentry *dentry);
extern int vmfs_proc_rmdir(struct dentry *dentry);
extern int vmfs_proc_unlink(struct dentry *dentry);
extern int vmfs_proc_flush(struct vmfs_sb_info *server, int32_t handle);
extern void vmfs_init_root_dirent(struct vmfs_sb_info *server, struct vmfs_fattr *fattr, struct super_block *sb);
extern int vmfs_proc_getattr(struct dentry *dir, struct vmfs_fattr *fattr);
extern int vmfs_proc_setattr(struct dentry *dir, struct vmfs_fattr *fattr);
extern int vmfs_proc_settime(struct dentry *dentry, struct vmfs_fattr *fattr);
extern int vmfs_proc_dskattr(struct dentry *dentry, struct kstatfs *kattr);
extern int vmfs_proc_read_link(struct vmfs_sb_info *server, struct dentry *dentry, char *buffer, int len);
extern int vmfs_proc_symlink(struct vmfs_sb_info *server, struct dentry *dentry, const char *oldpath);
extern int vmfs_proc_link(struct vmfs_sb_info *server, struct dentry *dentry, struct dentry *new_dentry);
extern void vmfs_install_ops(struct vmfs_ops *ops);
/* dir.c */
extern const struct file_operations vmfs_dir_operations;
extern const struct inode_operations vmfs_dir_inode_operations;
extern const struct inode_operations vmfs_dir_inode_operations_unix;
extern void vmfs_new_dentry(struct dentry *dentry);
extern void vmfs_renew_times(struct dentry *dentry);
/* cache.c */
extern int vmfs_fill_cache(struct file *filp, void *dirent, filldir_t filldir,
           struct vmfs_cache_control *ctrl, struct qstr *qname,
           struct vmfs_fattr *entry);
extern void vmfs_invalid_dir_cache(struct inode *dir);
extern void vmfs_invalidate_dircache_entries(struct dentry *parent);
extern struct dentry *vmfs_dget_fpos(struct dentry *dentry, struct dentry *parent, unsigned long fpos);
/* inode.c */
extern struct inode *vmfs_iget(struct super_block *sb, struct vmfs_fattr *fattr);
extern void vmfs_get_inode_attr(struct inode *inode, struct vmfs_fattr *fattr);
extern void vmfs_set_inode_attr(struct inode *inode, struct vmfs_fattr *fattr);
extern void vmfs_invalidate_inodes(struct vmfs_sb_info *server);
extern int vmfs_revalidate_inode(struct dentry *dentry);
extern int vmfs_getattr(struct vfsmount *mnt, struct dentry *dentry, struct kstat *stat);
extern int vmfs_notify_change(struct dentry *dentry, struct iattr *attr);
/* file.c */
extern const struct address_space_operations vmfs_file_aops;
extern const struct file_operations vmfs_file_operations;
extern const struct inode_operations vmfs_file_inode_operations;
/* ioctl.c */
extern int vmfs_ioctl(struct inode *inode, struct file *filp, unsigned int cmd, unsigned long arg);
/* symlink.c */
extern int vmfs_symlink(struct inode *inode, struct dentry *dentry, const char *oldname);
extern const struct inode_operations vmfs_link_inode_operations;
